version: "3.3"

services:
  app:
    image: delau/app
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./app:/srv
    ports:
        - "6666:80"
    env_file: .env

  mysql:
        image: mysql:5.7.29
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
        - "3306:3306"
        environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
        volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 6677:8080      